os:
  - linux

dist:
  - focal

compiler:
  - gcc

language:
  - python

python:
  - "2.7"
  - "3.8"

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install luajit python3-cffi -y

script:
  - buildtools/install-dependencies.sh
  - autoconf
  - ./configure
  - make
  - make tests
